name: Check PEP 8

on:
  pull_request_target:
    branches:
      - "main"

jobs:
  check_pep8:
    name: job check PEP 8
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: environment
        run: env

      - name: branches
        run: git branch -a

      - name: install
        run: pip3 install -r .github/workflows/check_pep8/requirements.txt

      - name: run test
        env:
          GITHUB_HEAD_REF: ${{ vars.GITHUB_HEAD_REF }}
        run: GITHUB_HEAD_REF=${GITHUB_HEAD_REF} bash .github/workflows/check_pep8/check_pep8.sh