name: Check PEP 8

on:
  pull_request_target:
    branches:
      - "main"

jobs:
  check_pep8:
    name: job check PEP 8
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: install docker
        run: bash .github/workflows/install_docker.sh

      - name: docker version
        run: docker version

      - name: run test
        run: bash .github/workflows/check_pep8/run.sh